export enum CompositionMode {
    Darken = "darken",
    Lighten = "lighten",
    Multiply = "multiply",
    Difference = "difference",
    Exclusion = "exclusion",
    SourceOver = "source-over",
    SourceIn = "source-in",
    SourceOut = "source-out",
    SourceAtop = "source-atop",
    DestinationOver = "destination-over",
    DestinationIn = "destination-in",
    DestinationOut = "destination-out",
    DestinationAtop = "destination-atop",
    Lighter = "lighter",
    Copy = "copy",
    Xor = "xor",
    Overlay = "overlay",
    Screen = "screen",
    ColorBurn = "color-burn",
    ColorDodge = "color-dodge",
    HardLight = "hard-light",
    SoftLight = "soft-light",
    Luminosity = "luminosity",
    Saturation = "saturation",
    Hue = "hue",
    Color = "color",
}